source : main
theme: minima
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 

title: Praveen Singh
description: 
- Machine Learning Engineer 
- Designing and developing machine learning and deep learning systems to solve real-life problems
